In [1]:
# Import pandas data analytics library
import pandas as pd

In [2]:
# Read in source CSV file of pizza sales
data = pd.read_csv('PizzaSales.csv')

In [3]:
# Convert CSV to DataFrame
df = pd.DataFrame(data)

In [4]:
# Display first 15 orders
df.head(15)

,order_id,pizza_id,quantity,order_date,order_time,unit_price,total_price,pizza_size,pizza_category,pizza_ingredients,pizza_name,Unnamed: 11
0,1,hawaiian_m,1,1/1/15,11:38:36,13.25,13.25,M,Classic,"Sliced Ham, Pineapple, Mozzarella Cheese",The Hawaiian Pizza,NaN
1,2,classic_dlx_m,1,1/1/15,11:57:40,16.00,16.00,M,Classic,"Pepperoni, Mushrooms, Red Onions, Red Peppers,...",The Classic Deluxe Pizza,NaN
2,3,five_cheese_l,1,1/1/15,11:57:40,18.50,18.50,L,Veggie,"Mozzarella Cheese, Provolone Cheese, Smoked Go...",The Five Cheese Pizza,NaN
3,4,ital_supr_l,1,1/1/15,11:57:40,20.75,20.75,L,Supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni...",The Italian Supreme Pizza,NaN
4,5,mexicana_m,1,1/1/15,11:57:40,16.00,16.00,M,Veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",The Mexicana Pizza,NaN
5,6,thai_ckn_l,1,1/1/15,11:57:40,20.75,20.75,L,Chicken,"Chicken, Pineapple, Tomatoes, Red Peppers, Tha...",The Thai Chicken Pizza,NaN
6,7,ital_supr_m,1,1/1/15,12:12:28,16.50,16.50,M,Supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni...",The Italian Supreme Pizza,NaN
7,8,prsc_argla_l,1,1/1/15,12:12:28,20.75,20.75,L,Supreme,"Prosciutto di San Daniele, Arugula, Mozzarella...",The Prosciutto and Arugula Pizza,NaN
8,9,ital_supr_m,1,1/1/15,12:16:31,16.50,16.50,M,Supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni...",The Italian Supreme Pizza,NaN
9,10,ital_supr_m,1,1/1/15,12:21:30,16.50,16.50,M,Supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni...",The Italian Supreme Pizza,NaN
10,11,bbq_ckn_s,1,1/1/15,12:29:36,12.75,12.75,S,Chicken,"Barbecued Chicken, Red Peppers, Green Peppers,...",The Barbecue Chicken Pizza,NaN
11,12,the_greek_s,1,1/1/15,12:29:36,12.00,12.00,S,Classic,"Kalamata Olives, Feta Cheese, Tomatoes, Garlic...",The Greek Pizza,NaN
12,13,spinach_supr_s,1,1/1/15,12:50:37,12.50,12.50,S,Supreme,"Spinach, Red Onions, Pepperoni, Tomatoes, Arti...",The Spinach Supreme Pizza,NaN
13,14,spinach_supr_s,1,1/1/15,12:51:37,12.50,12.50,S,Supreme,"Spinach, Red Onions, Pepperoni, Tomatoes, Arti...",The Spinach Supreme Pizza,NaN
14,15,classic_dlx_s,1,1/1/15,12:52:01,12.00,12.00,S,Classic,"Pepperoni, Mushrooms, Red Onions, Red Peppers,...",The Classic Deluxe Pizza,NaN

In [5]:
# Create separate DataFrame with units sold per pizza type, ordered from most to least popular
popular_pizzas = df['pizza_name'].value_counts()

In [6]:
# Display top 10 most popular pizza types
popular_pizzas.head(10)

pizza_name
The Classic Deluxe Pizza        2416
The Barbecue Chicken Pizza      2372
The Hawaiian Pizza              2370
The Pepperoni Pizza             2369
The Thai Chicken Pizza          2315
The California Chicken Pizza    2302
The Sicilian Pizza              1887
The Spicy Italian Pizza         1887
The Southwest Chicken Pizza     1885
The Four Cheese Pizza           1850
Name: count, dtype: int64

In [7]:
# Convert DataFrame to Excel file and store on local filesystem
popular_pizzas.to_excel('PopularPizzas.xlsx')

In [8]:
# As a test, un-comment and run this to change from descending to ascending order. Excel file should update upon closing and re-opening.
# popular_pizzas = popular_pizzas.iloc[::-1]
# popular_pizzas.to_excel('PopularPizzas.xlsx')